Allow users to opt-in to SAML validation errors from ruby-saml
DigitalNZ/omniauth-realme pull request #19
Opened 2020-08-12 04:14 UTC by eoinkelly

Getting exceptions from SAML validation errors can be really useful for
debugging, especially near the start of a project or when working with a
new IdP implementation. This opt-in setting allows users to choose to
see them.

The example in the docs recommends turning them on for Rails development
env only.

This change is backwards compatible. If the option is not specified it
defaults to off (which is the behaviour before this change)

2020-08-12 10:21 UTC, hapiben requested changes

2020-08-12 10:21 UTC, hapiben commented on README.md
> +  raise_exceptions_for_saml_validation_errors = true if Rails.env.development? # default: false
Do you need the `config` here?

```suggestion
  config.raise_exceptions_for_saml_validation_errors = Rails.env.development? # default: false
```

2020-08-13 02:32 UTC, eoinkelly commented on README.md
> +  raise_exceptions_for_saml_validation_errors = true if Rails.env.development? # default: false
I do indeed - good catch!

2020-08-13 02:36 UTC, hapiben approved these changes

2020-08-13 02:36 UTC, merged

2020-08-13 02:36 UTC, hapiben commented
Thanks @eoinkelly. Merged.